# Generated by Django 6.0.6 on 2026-06-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0002_evaluation_evaluationfactor_recommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('scopus', 'Scopus'), ('openalex', 'OpenAlex'), ('semantic_scholar', 'Semantic Scholar')], max_length=40)),
                ('source_identifier', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('authors', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('citation_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Documento bibliográfico',
                'verbose_name_plural': 'Documentos bibliográficos',
                'ordering': ['-citation_count', '-year'],
                'unique_together': {('source', 'source_identifier')},
            },
        ),
        migrations.CreateModel(
            name='LiteratureQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('scopus', 'Scopus'), ('openalex', 'OpenAlex'), ('semantic_scholar', 'Semantic Scholar')], max_length=40)),
                ('query_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=40)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_queries', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Consulta bibliográfica',
                'verbose_name_plural': 'Consultas bibliográficas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactorEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_keywords', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(default=0)),
                ('evaluation_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='evaluations.evaluationfactor')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_evidence', to='literature.literaturedocument')),
            ],
            options={
                'verbose_name': 'Evidencia por factor',
                'verbose_name_plural': 'Evidencias por factor',
                'ordering': ['-relevance_score'],
                'unique_together': {('evaluation_factor', 'document')},
            },
        ),
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_results', to='literature.literaturedocument')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='literature.literaturequery')),
            ],
            options={
                'verbose_name': 'Resultado de consulta',
                'verbose_name_plural': 'Resultados de consulta',
                'ordering': ['position', '-relevance_score'],
                'unique_together': {('query', 'document')},
            },
        ),
    ]
