# Generated by Django 6.0.6 on 2026-06-19 21:18

import django.db.models.deletion
from django.db import migrations, models


def link_queries_to_evaluation_factors(apps, schema_editor):
    LiteratureQuery = apps.get_model("literature", "LiteratureQuery")
    EvaluationFactor = apps.get_model("evaluations", "EvaluationFactor")
    FactorKeyword = apps.get_model("evaluations", "FactorKeyword")

    for query in LiteratureQuery.objects.order_by("evaluation_id", "id").iterator():
        query_text = query.query_text.casefold()
        candidates = []

        for evaluation_factor in EvaluationFactor.objects.filter(
            evaluation_id=query.evaluation_id,
        ).order_by("factor_id"):
            keywords = FactorKeyword.objects.filter(
                factor_id=evaluation_factor.factor_id,
            ).values_list("keyword", flat=True)
            matches = sum(
                1 for keyword in keywords if keyword and keyword.casefold() in query_text
            )
            if matches:
                candidates.append((matches, evaluation_factor.pk))

        if not candidates:
            raise RuntimeError(
                f"No se pudo identificar el factor de la consulta bibliografica {query.pk}."
            )

        best_score = max(score for score, _ in candidates)
        best_candidates = [
            evaluation_factor_id
            for score, evaluation_factor_id in candidates
            if score == best_score
        ]

        if len(best_candidates) != 1:
            raise RuntimeError(
                f"La consulta bibliografica {query.pk} coincide con varios factores."
            )

        query.evaluation_factor_id = best_candidates[0]
        query.save(update_fields=["evaluation_factor"])


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_evaluationfactor_unique_together_and_more'),
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factorevidence',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='literaturedocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='queryresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='literaturequery',
            name='evaluation_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_queries', to='evaluations.evaluationfactor'),
        ),
        migrations.RunPython(
            link_queries_to_evaluation_factors,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='literaturequery',
            name='evaluation_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_queries', to='evaluations.evaluationfactor'),
        ),
        migrations.RemoveField(
            model_name='literaturequery',
            name='evaluation',
        ),
        migrations.AddConstraint(
            model_name='factorevidence',
            constraint=models.UniqueConstraint(fields=('evaluation_factor', 'document'), name='literature_evidence_factor_document_unique'),
        ),
        migrations.AddConstraint(
            model_name='factorevidence',
            constraint=models.CheckConstraint(condition=models.Q(('relevance_score__range', (0, 12))), name='literature_evidence_relevance_score_valid'),
        ),
        migrations.AddConstraint(
            model_name='literaturedocument',
            constraint=models.UniqueConstraint(fields=('source', 'source_identifier'), name='literature_document_source_identifier_unique'),
        ),
        migrations.AddConstraint(
            model_name='literaturedocument',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['scopus', 'openalex', 'semantic_scholar'])), name='literature_document_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='literaturedocument',
            constraint=models.CheckConstraint(condition=models.Q(('source_identifier', ''), _negated=True), name='literature_document_identifier_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='literaturedocument',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='literature_document_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='literaturedocument',
            constraint=models.CheckConstraint(condition=models.Q(('year__isnull', True), ('year__range', (1900, 2100)), _connector='OR'), name='literature_document_year_valid'),
        ),
        migrations.AddConstraint(
            model_name='literaturequery',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['scopus', 'openalex', 'semantic_scholar'])), name='literature_query_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='literaturequery',
            constraint=models.CheckConstraint(condition=models.Q(('query_text', ''), _negated=True), name='literature_query_text_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='literaturequery',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'completed', 'failed'])), name='literature_query_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='literaturequery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status__in', ['completed', 'failed'])), models.Q(('completed_at__isnull', True), ('status__in', ['pending', 'running'])), _connector='OR'), name='literature_query_completion_consistent'),
        ),
        migrations.AddConstraint(
            model_name='literaturequery',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'failed'), ('error_message', ''), _connector='OR'), name='literature_query_error_only_when_failed'),
        ),
        migrations.AddConstraint(
            model_name='queryresult',
            constraint=models.UniqueConstraint(fields=('query', 'document'), name='literature_query_document_unique'),
        ),
        migrations.AddConstraint(
            model_name='queryresult',
            constraint=models.UniqueConstraint(fields=('query', 'position'), name='literature_query_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='queryresult',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='literature_query_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='queryresult',
            constraint=models.CheckConstraint(condition=models.Q(('relevance_score__range', (0, 12))), name='literature_query_relevance_score_valid'),
        ),
    ]
