# Generated by Codex on 2026-06-27

from django.db import migrations, models


VALID_SOURCES = ["scopus", "openalex"]


def purge_semantic_scholar_source(apps, schema_editor):
    LiteratureDocument = apps.get_model("literature", "LiteratureDocument")
    LiteratureQuery = apps.get_model("literature", "LiteratureQuery")

    LiteratureQuery.objects.filter(source="semantic_scholar").delete()
    LiteratureDocument.objects.filter(source="semantic_scholar").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0002_alter_factorevidence_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(
            purge_semantic_scholar_source,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="literaturedocument",
            name="literature_document_source_valid",
        ),
        migrations.RemoveConstraint(
            model_name="literaturequery",
            name="literature_query_source_valid",
        ),
        migrations.AlterField(
            model_name="literaturedocument",
            name="source",
            field=models.CharField(
                choices=[("scopus", "Scopus"), ("openalex", "OpenAlex")],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="literaturequery",
            name="source",
            field=models.CharField(
                choices=[("scopus", "Scopus"), ("openalex", "OpenAlex")],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="literaturedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(source__in=VALID_SOURCES),
                name="literature_document_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="literaturequery",
            constraint=models.CheckConstraint(
                condition=models.Q(source__in=VALID_SOURCES),
                name="literature_query_source_valid",
            ),
        ),
    ]
