# Generated by Django 6.0.6 on 2026-06-19 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'evaluator'])), name='users_profile_role_valid'),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX users_auth_user_email_ci_unique "
                "ON auth_user (LOWER(email)) WHERE email <> '';"
            ),
            reverse_sql="DROP INDEX IF EXISTS users_auth_user_email_ci_unique;",
        ),
    ]
