# Generated by Django 6.0.6 on 2026-06-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('default_suggested_importance', models.PositiveSmallIntegerField(choices=[(1, 'Irrelevante'), (2, 'Opcional'), (3, 'Importante'), (4, 'Fundamental')], default=2)),
                ('scope', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo'), ('Ambos', 'Ambos')], default='Interno', max_length=20)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='evaluations.dimension')),
            ],
            options={
                'verbose_name': 'Factor',
                'verbose_name_plural': 'Factores',
                'ordering': ['dimension__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subfactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactors', to='evaluations.factor')),
            ],
            options={
                'verbose_name': 'Subfactor',
                'verbose_name_plural': 'Subfactores',
                'ordering': ['factor__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FactorKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='evaluations.factor')),
            ],
            options={
                'verbose_name': 'Palabra clave de factor',
                'verbose_name_plural': 'Palabras clave de factores',
                'ordering': ['factor__name', 'keyword'],
                'unique_together': {('factor', 'keyword')},
            },
        ),
    ]
