# Generated by Django 6.0.6 on 2026-06-19 21:18

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluation_evaluationfactor_recommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationfactor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationsubfactor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='factorkeyword',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dimension',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='evaluation_dimension_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='dimension',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='evaluation_dimension_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('software_name', ''), _negated=True), name='evaluation_software_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('context', ''), _negated=True), name='evaluation_context_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'suggested_ready', 'factors_ready', 'subfactors_ready', 'completed'])), name='evaluation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.UniqueConstraint(fields=('evaluation', 'factor'), name='evaluation_factor_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(('literature_importance__isnull', True), ('literature_importance__range', (1, 4)), _connector='OR'), name='evaluation_literature_importance_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(('expert_importance__isnull', True), ('expert_importance__range', (1, 4)), _connector='OR'), name='evaluation_expert_importance_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_importance__range', (1, 4))), name='evaluation_suggested_importance_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(('decision_maker_importance__isnull', True), ('decision_maker_importance__range', (1, 4)), _connector='OR'), name='evaluation_decision_importance_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(('relative_importance__isnull', True), ('relative_importance__range', (1, 4)), _connector='OR'), name='evaluation_relative_importance_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(('selected_scope__in', ['Interno', 'Externo'])), name='evaluation_selected_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(('mean_weight__isnull', True), ('mean_weight__range', (1, 4)), _connector='OR'), name='evaluation_mean_weight_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(('foda__in', ['', 'Fortaleza', 'Oportunidad', 'Debilidad', 'Amenaza'])), name='evaluation_foda_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationfactor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_relevant', False), ('relative_importance__isnull', True)), models.Q(('is_relevant', False), ('relative_importance', 1)), models.Q(('is_relevant', True), ('relative_importance__gte', 2)), _connector='OR'), name='evaluation_relevance_consistent'),
        ),
        migrations.AddConstraint(
            model_name='evaluationsubfactor',
            constraint=models.UniqueConstraint(fields=('evaluation_factor', 'subfactor'), name='evaluation_subfactor_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='evaluationsubfactor',
            constraint=models.CheckConstraint(condition=models.Q(('compliance__range', (1, 4))), name='evaluation_subfactor_compliance_valid'),
        ),
        migrations.AddConstraint(
            model_name='factor',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='evaluation_factor_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='factor',
            constraint=models.CheckConstraint(condition=models.Q(('default_suggested_importance__range', (1, 4))), name='evaluation_factor_default_importance_valid'),
        ),
        migrations.AddConstraint(
            model_name='factor',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['Interno', 'Externo', 'Ambos'])), name='evaluation_factor_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='factor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='evaluation_factor_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='factorkeyword',
            constraint=models.CheckConstraint(condition=models.Q(('keyword', ''), _negated=True), name='evaluation_keyword_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='factorkeyword',
            constraint=models.UniqueConstraint(models.F('factor'), django.db.models.functions.text.Lower('keyword'), name='evaluation_keyword_factor_value_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.CheckConstraint(condition=models.Q(('code__in', ['', 'A', 'B', 'C'])), name='evaluation_recommendation_code_valid'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='evaluation_recommendation_text_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='subfactor',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='evaluation_subfactor_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='subfactor',
            constraint=models.UniqueConstraint(models.F('factor'), django.db.models.functions.text.Lower('name'), name='evaluation_subfactor_factor_name_ci_unique'),
        ),
    ]
